### ISSUE TITLE
on linux with clock in UTC executes as future time

### ISSUE THREAD

**Issue by davidwalter0** [openpubkey/openpubkey#104]
```shell
cd examples/simple
go build
./simple
```
or mfa
or google

login via google oidc returns 
```
failed to exchange token: issuedAt of token is in the future: \
    (iat: 2024-02-22 14:40:31 -0500 EST, now with offset: 2024-02-22 19:40:22 +0000 UTC)
```

**Comment by EthanHeilman** [comment]
Thanks for this bug report. I'll be taking a look at it tomorrow

**Comment by EthanHeilman** [comment]
@davidwalter0 In the Google example this value in the ID Token is set by Google and [the error message is generated by our OIDC library before we get the token](https://pkg.go.dev/github.com/zitadel/oidc/v2/pkg/oidc). Can you confirm that your system clock is correct?

I can adjust the allowed clock skew. Looking into what the standard allowed clock skew adjustment is.
```golang
options := []rp.Option{
rp.WithCookieHandler(cookieHandler),
rp.WithVerifierOpts(
	rp.WithIssuedAtOffset(5*time.Second), rp.WithNonce(
		func(ctx context.Context) string { return cicHash })),
}
```

**Comment by EthanHeilman** [comment]
Increased the IssuedAt time to one minute, can you try again with this change? @davidwalter0

**Comment by EthanHeilman** [comment]
Closing this for now. https://github.com/openpubkey/openpubkey/pull/108 increased out clock skew forgiveness to 1 minute which should fix the issue. If you are still running into this, please close.
