### ISSUE TITLE
Move all tests over to testify/require

### ISSUE THREAD

**Issue by EthanHeilman** [openpubkey/openpubkey#175]
Currently some tests aren't using the require pattern as shown below:

https://github.com/openpubkey/openpubkey/blob/57897d7475b79ec089285b3267598dab3fdd0153/examples/ssh/opkssh/cli_test.go#L55-L58

We should move all of the remaining tests over to require:

https://github.com/openpubkey/openpubkey/blob/03c27ef14492728c0125c3691b35b1a79b3d1e09/client/opkclient_test.go#L78-L81

**Comment by roceb** [comment]
I could work on this.

**Comment by EthanHeilman** [comment]
@roceb Let me know if you have any questions. Are you on the OpenSSF OpenPubkey slack channel?

**Comment by roceb** [comment]
@EthanHeilman no I am not. I will join

**Comment by EthanHeilman** [comment]
@roceb Go here click join our slack and you will get an invite and can join the openSSF slack

https://openssf.org/getinvolved/
