### ISSUE TITLE
Should client return PK Tokens by reference or value?

### ISSUE THREAD

**Issue by EthanHeilman** [openpubkey/openpubkey#184]
It can be confusing to reason about PK Tokens if they are passed by reference as it can change under us. Nothing really surprising here, but we should think if we want to pass by value to increase safety and make the code easier to reason able.

Pass by reference:
`func (o *OpkClient) Auth(ctx context.Context, opts ...AuthOpts) (*pktoken.PKToken, error)`

Pass by value
`func (o *OpkClient) Auth(ctx context.Context, opts ...AuthOpts) (pktoken.PKToken, error)`

Since some of the struct variables as also references, we would probably want to change them to pass by reference or no longer expose them and use Getters and Setters to manage them. Pass by value would be a fairly big breaking change so if we want to make it, we should make it now.

```go
type PKToken struct {
	raw []byte // the original, raw representation of the object

	Payload []byte     // decoded payload
	Op      *Signature // Provider Signature
	Cic     *Signature // Client Signature
	Cos     *Signature // Cosigner Signature

	// We keep the tokens around as  unmarshalled values can no longer be verified
	OpToken  []byte // Base64 encoded ID Token signed by the OP
	CicToken []byte // Base64 encoded Token signed by the Client
	CosToken []byte // Base64 encoded Token signed by the Cosigner

	// FreshIDToken is the refreshed ID Token. It has a different payload from
	// other tokens and must be handled separately.
	// It is only used for POP Authentication
	FreshIDToken []byte // Base64 encoded Refreshed ID Token
}
```

### Pass by value (Yea)

1. "As a proponent of functional programming, I personally I favour pass-by-value for the reasons you mention. I detested hidden mutable state. IMO, it should be up to the computers to optimise things, not programmers "

### Pass by value (Nay)
1. "One downside to pass by value is that the return values cannot be nil, which might break some of the error handling and may be an odd design pattern for Go"
2. Pass by reference but deep copy the reference, gets you everything pass by value gets you but involves minimal changes

## History
I ran into this issue while writing following test.

This code will result in pkt1 being the same as pkt2 despite pkt1 originally not having a refreshed ID Token. This is because pkt1 and pkt2 point to the same object
```go
pkt1, err := c.Auth(context.Background())
require.NoError(t, err)


pkt2, err := c.Refresh(context.Background())
require.NoError(t, err)

pkt1Com, err := pkt1.Compact()
require.NoError(t, err)

pkt2Com, err := pkt2.Compact()
require.NoError(t, err)
require.NotEqual(t, string(pkt1Com), string(pkt2Com))
```

If we get the compact representation before calling refresh the test passes
```go
pkt1, err := c.Auth(context.Background())
require.NoError(t, err)
pkt1Com, err := pkt1.Compact()
require.NoError(t, err)

pkt2, err := c.Refresh(context.Background())
require.NoError(t, err)

pkt2Com, err := pkt2.Compact()
require.NoError(t, err)
require.NotEqual(t, string(pkt1Com), string(pkt2Com))
```

**Comment by mrjoelkamp** [comment]
One downside to pass by value is that the return values cannot be `nil`, which will break some of the error handling  (`if err != nil`) and may be an odd design pattern for Go.

**Comment by EthanHeilman** [comment]
> One downside to pass by value is that the return values cannot be nil, which might break some of the error handling and may be an odd design pattern for Go.

@mrjoelkamp Good point. I could do a deep copy of the pktoken and pass a reference to that.

**Comment by EthanHeilman** [comment]
I'm leaning toward pass by reference but do a deep copy

**Comment by EthanHeilman** [comment]
Resolved this by doing a deep copy
