### ISSUE TITLE
We should use algorithm from public key rather than alg from token in verification

### ISSUE THREAD

**Issue by EthanHeilman** [openpubkey/openpubkey#185]
In the code below, we use the alg set in the ID Token to verify the ID Token. This does not present a security risk because we also check it is the expected algorithm and for GQ256 we need to do this. However we should check that public key in `pubKeyRecord.PublicKey` is RS256. 

```go
	algStr := idt.GetSignature().GetProtectedClaims().Alg
	if algStr == "" {
		return fmt.Errorf("provider algorithm type missing")
	}
	alg := jwa.SignatureAlgorithm(algStr)
	if alg != gq.GQ256 && v.options.GQOnly {
		return fmt.Errorf("non-GQ signatures are not supported")
	}

	switch alg {
	case gq.GQ256:
		if err := v.verifyGQSig(ctx, idt); err != nil {
			return fmt.Errorf("error verifying OP GQ signature on PK Token: %w", err)
		}
	case jwa.RS256:
		pubKeyRecord, err := v.providerPublicKey(ctx, idToken)
		if err != nil {
			return fmt.Errorf("failed to get OP public key: %w", err)
		}
		alg := jwa.SignatureAlgorithm(algStr)
		if _, err := jws.Verify(idToken, jws.WithKey(alg, pubKeyRecord.PublicKey)); err != nil {
			return err
		}
	}
```

**Comment by thebigbone** [comment]
I would like to work on this. Are you talking about [this](https://github.com/openpubkey/openpubkey/blob/main/providers/providerverifier.go#L129) file and line of it?

**Comment by EthanHeilman** [comment]
@thebigbone That is the line and anywhere else you find it. We should always be checking that alg we are verifying against matches algorithm of the public key downloaded from the JWKS.

Glad to have your help =)

**Comment by thebigbone** [comment]
> @thebigbone That is the line and anywhere else you find it. We should always be checking that alg we are verifying against matches algorithm of the public key downloaded from the JWKS.

Got it.

> Glad to have your help =)

Happy to help!

**Comment by EthanHeilman** [comment]
@thebigbone If you want to talk through any of this feel free to drop by the OpenPubkey slack channel on the OpenSSF slack. I'm usually around http://slack.openssf.org/
