### ISSUE TITLE
PK Token Compact Representation

### ISSUE THREAD

**Issue by EthanHeilman** [openpubkey/openpubkey#31]
[RFC-7515: JWS (JSON Web Signatures)](https://www.rfc-editor.org/rfc/rfc7515.html) specifies two serialization formats for JWS: JSON and Compact.
```
Two closely related serializations for JWSs are defined.  The JWS
Compact Serialization is a compact, URL-safe representation intended
for space-constrained environments such as HTTP Authorization headers
and URI query parameters.  The JWS JSON Serialization represents JWSs
as JSON objects and enables multiple signatures and/or MACs to be
applied to the same content.
```

[RFC-7515: Section 7.1](https://www.rfc-editor.org/rfc/rfc7515.html#section-7.1) defines the Compact Serialization format as:
```
7.1  JWS Compact Serialization

   The JWS Compact Serialization represents digitally signed or MACed
   content as a compact, URL-safe string.  This string is:

      BASE64URL(UTF8(JWS Protected Header)) || '.' ||
      BASE64URL(JWS Payload) || '.' ||
      BASE64URL(JWS Signature)

   Only one signature/MAC is supported by the JWS Compact Serialization
   and it provides no syntax to represent a JWS Unprotected Header
   value.
```

Note that this means the JWS Compact Serialization only supports one signature. This prevents us from using it as-is for PK Tokens as our PK Tokens are JWS with more than one signature.

While the JWS JSON Serialization supports multiple signatures and thus can easily support our PK Tokens the RFC says: `This representation is neither optimized for compactness nor URL-safe.`

It would be useful for OpenPubkey to have a compact, URL-safe serialization. I am proposing the following format for JWS Compact Serialization format.

## JWS Compact Serialization for multiple signatures

(JWS Protected Header1,Signature1) through (JWS Protected HeaderN,SignatureN) 

```
      BASE64URL(JWS Payload) || ':' ||
      BASE64URL(UTF8(JWS Protected Header1)) || ':' ||
      BASE64URL(JWS Signature1)  || ':' ||
      BASE64URL(UTF8(JWS Protected Header2)) || ':' ||
      BASE64URL(JWS Signature2)  || ':' ||
      ...
      BASE64URL(UTF8(JWS Protected HeaderN)) || ':' ||
      BASE64URL(JWS SignatureN) 
```

in golang

```golang
func FromCompact(pktCom []byte) (*PKToken, error) {
	splitCom := bytes.Split(pktCom, []byte(":"))
	if len(splitCom) == 5 {
		return &PKToken{
			Payload: splitCom[0],
			OpPH:    splitCom[1],
			OpSig:   splitCom[2],
			CicPH:   splitCom[3],
			CicSig:  splitCom[4],
			CosPH:   nil,
			CosSig:  nil,
		}, nil
	} else if len(splitCom) == 7 {
		return &PKToken{
			Payload: splitCom[0],
			OpPH:    splitCom[1],
			OpSig:   splitCom[2],
			CicPH:   splitCom[3],
			CicSig:  splitCom[4],
			CosPH:   splitCom[5],
			CosSig:  splitCom[6],
		}, nil
	} else {
		return nil, fmt.Errorf("A valid PK Token should have exactly two or three (protected header, signature pairs), but has %d signatures", len(splitCom))
	}
}

func (p *PKToken) ToCompact() []byte {
	if p.Payload == nil {
		panic(fmt.Errorf("Payload can not be nil"))
	}

	var buf bytes.Buffer
	buf.WriteString(string(p.Payload))
	buf.WriteByte(':')
	buf.WriteString(string(p.OpPH))
	buf.WriteByte(':')
	buf.WriteString(string(p.OpSig))
	buf.WriteByte(':')
	buf.WriteString(string(p.CicPH))
	buf.WriteByte(':')
	buf.WriteString(string(p.CicSig))

	if p.CosPH != nil {
		buf.WriteByte(':')
		buf.WriteString(string(p.CosPH))
		buf.WriteByte(':')
		buf.WriteString(string(p.CosSig))
	}

	pktCom := buf.Bytes()
	return pktCom
}
```

**Comment by lgmugnier** [comment]
It would be really nice if whatever compact representation we had was appendable. So, for instance, you have a compact representation of your PK Token already and a new cosigner wants to add on their signature. In this case, you should be able to append it to the existing PK Token (`[pktoken compact] + [new cosigner sig]`) without having to marshal and unmarshal things. Because different languages might have different json or other formatting quirks, this helps make sure that it remains perfectly verifiable down the line because we're maintaining that original base64 encoding

**Comment by EthanHeilman** [comment]
I agree, amenability should be builtin.
