### ISSUE TITLE
GHA Runner VM Entropy for Key Generation

### ISSUE THREAD

**Issue by mrjoelkamp** [openpubkey/openpubkey#50]
# Problem <a href="#user-content-problem" id="problem">#</a>

The `Sign()` method generates ephemeral keys for signing attestations shown here:
https://github.com/openpubkey/signed-attestation/blob/f64048341ecd651ed894f094ab70213d20ee6bbb/opk.go#L30-L33

Using `GenKeyPair()` in `utils`:
https://github.com/openpubkey/openpubkey/blob/f662c2ce7ecfd68427be19374409a927b8898223/util/files.go#L100-L109

Depending upon the system on which this is running, the entropy available (and sources it is derived from) may not be very high quality. The quality of the entropy source is important in determining how secure the resulting signatures are by ensuring that we are generating unpredictable private keys.

A planned use-case is running this as a GitHub Action (GHA). [GHAs run on Virtual Machines](https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#the-components-of-github-actions). Typically, VMs are poor sources of entropy and are very deterministic unless effort is made to provision them with a quality entropy source.

There are several [mitigating factors](#user-content-mitigating-factors) for key compromise built into the solution. Although, identifying the entropy source for GHA runners and improving it if needed, is another mitigating factor for preventing key compromise.

## Entropy source for GHA runners

It appears that the ubuntu VM images have been updated to include `haveged` https://github.com/actions/runner-images/issues/672. Unsure if that is the latest change w.r.t. entropy sources in GHA VMs.

>haveged is a daemon — derived from [the HAVEGE algorithm](http://www.irisa.fr/caps/projects/hipsor/) — designed to help (the kernel) gather entropy from more sources (than the kernel itself does). It is common to install it on physical hosts to gather entropy faster from their entropy-rich environment. However, it is not recommended to use it in virtual machines, since the very reasons that make them prone to entropy starvation will hinder, if not defeat, HAVEGE (or the quality — randomness — of the entropy it will gather).

## Testing the VM configuration

A lot of sources point to this [writeup](https://security.stackexchange.com/a/34552) about `HAVAGE` (the algorithm that `haveged` is based on). It discusses how it uses the [rdtsc](http://en.wikipedia.org/wiki/Time_Stamp_Counter) (x86 processor time stamp counter with sub-nanosecond precision) as a source of entropy. 

They highlight three possible VM configurations for how `rdtsc` is implemented:
>For a virtual machine system, there are three choices with regards to this instruction:
>  1. Let the instruction go to the hardware directly.
>  2. Trap the instruction and emulate it.
>  3. Disable the instruction altogether.

I created a GHA action to run the example code to gain some insight into how the GHA VMs might be configured for `rdtsc` and good news! It appears that the `rdtsc` instruction is configured to go directly to the host hardware. Which is the best possible option of the three configurations.

See the action run here https://github.com/mrjoelkamp/gha-vm-rdtsc-test/actions/runs/6720417160/job/18264356488
Looking for a value between 10 - 100.
result:
```bash
average : 34.859
```

This result determines whether the GHA VMs are configured to use the host's `rdtsc` derived from hardware as opposed to being emulated or not available. If it failed (and the entropy was emulated or hardcoded) that could be a major issue.

What it doesn't answer, is whether it is appropriate to use the GHA VM's entropy source (`haveged`) for RNG when generating cryptographic key material. We also assume that the GHA VM will continue to provide an environment where we can securely generate key material and perform cryptographic operations in.

# Solution <a href="#user-content-solution" id="solution">#</a>

In addition to the current Go based KDF and crypto library, I recommend that OpenPubKey support cloud provider KMS solutions for cryptographic functions (AWS, GCP, Azure, Hashicorp, etc.). A lot of these systems are backed by Hardware Security Modules (HSMs) with high entropy RNG.  

For example:
> AWS KMS key generation is performed on the AWS KMS HSMs. The HSMs implement a hybrid random number generator that uses the [NIST SP800-90A Deterministic Random Bit Generator (DRBG) CTR_DRBG using AES-256](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-90Ar1.pdf). It is seeded with a nondeterministic random bit generator with 384-bits of entropy and updated with additional entropy to provide prediction resistance on every call for cryptographic material.

There are many other added benefits to supporting external KMS solutions as well:
- Controlled execution environment that is optimized for cryptographic operations
- Runtime access to private keys not accessible by software interface

# Mitigating Factors <a href="#user-content-mitigating-factors" id="mitigating-factors">#</a>

## Ephemeral Key Lifetime
If the system only trusts the ephemeral keys to sign data in a short time frame, the compromise of the private ephemeral may be of little significance. Although, depending on how deterministic the RNG is, an attacker could potentially determine the private key ahead of ephemeral key generation with significant statistical probability.

## Transparency Log
Including a Transparency Log to store signatures that could be monitored by publishers to determine if an actor forged a signature using a compromised key and generated a signature outside of their control. Although, this countermeasure would be reactive as opposed to preventative and requires active monitoring and alerting.

## Layered Signing
The OPK One Time Signature could also mitigate this issue by providing a hash of the image in the payload that is signed by the Identity Provider. If an image was modified and signed by someone who had compromised a user signing key, the hash comparison would fail for the modified image. This requires that the verification client implement this check.

**Comment by EthanHeilman** [comment]
OpenPubkey should support KMS and HSMs. This is the ideal solution for people that use KSM or HSMs. Everything I am going to say next is thinking about how to support openpubkey for users that may not have or want to use KSM/HSMs.

## rdrand, rdseed, RNDR, /dev/hwrng
I don't see any harm in using `HAVAGE` as an additional source of entropy. I think if we are concerned about rand.Reader not providing sufficient entropy one of the first places we should look at is the [x86 `rdrand` and `rdseed` instructions.](https://en.wikipedia.org/wiki/RDRAND) [I modified your test code ](https://github.com/EthanHeilman/gha-vm-rdtsc-test/blob/main/test.c) to show that GHA ubuntu runner has access to the `rdrand` and `rdseed` instructions.

The action output is here: https://github.com/EthanHeilman/gha-vm-rdtsc-test/actions/runs/6757557761/job/18368221015

We could use [RDRAND-Tester](https://github.com/cjee21/RDRAND-Tester) to check if rdrand is available on the system and fail if it isn't evaluable. While `rdrand` and `rdseed` only exists on x86. we should get ARM support by using the [RNDR ARM instruction.](https://developer.arm.com/documentation/ka005114/latest/)

Linux provides the `/dev/hwrng` device which provides a nice place to plug in hardware sources of entropy. RaspberryPI exposes their HW RNG via that device. Not sure if all ARM systems do this. Some [hypervisors ](https://www.exoscale.com/syslog/random-numbers-generation-in-virtual-machines/) and [emulators](https://wiki.qemu.org/Features/VirtIORNG) use `/dev/hwrng` as a way of exposing true random number generation to each of their host virtual machines.

## Additional hardening in Github Actions

This might be overkill but we could use the `SHA3(ACTIONS_ID_TOKEN_REQUEST_TOKEN)`, and in case of GQ signatures `SHA3(OP RSA Signature)`, as an additional source of entropy on top of what rand.Reader provides. The preimage resistance of SHA3 should protect the value from leaking assuming the github OpenID Provider does not have an entropy generation problem and is not generating low entropy tokens and RSA signatures.

**Comment by mrjoelkamp** [comment]
> ## rdrand, rdseed, RNDR, /dev/hwrng
> I don't see any harm in using `HAVAGE` as an additional source of entropy. I think if we are concerned about rand.Reader not providing sufficient entropy one of the first places we should look at is the [x86 `rdrand` and `rdseed` instructions.](https://en.wikipedia.org/wiki/RDRAND) [I modified your test code ](https://github.com/EthanHeilman/gha-vm-rdtsc-test/blob/main/test.c) to show that GHA ubuntu runner has access to the `rdrand` and `rdseed` instructions.
> 
> The action output is here: https://github.com/EthanHeilman/gha-vm-rdtsc-test/actions/runs/6757557761/job/18368221015

Very nice! It looks like the GHA runners are fairly well provisioned with entropy sources. Agreed that this will be good support for users without KMS/HSM access. Thanks for taking a look at it!

**Comment by EthanHeilman** [comment]
@mrjoelkamp Closing this. If you think this should be reopened please reopen.
