### ISSUE TITLE
sensitive data in `crypto` package

### ISSUE THREAD

**Issue by mrjoelkamp** [openpubkey/openpubkey#53]
Identified in #48 

The `crypto` package is used for ephemeral key generation and `cic` signing:
https://github.com/openpubkey/openpubkey/blob/cdf1ff6d3d52274db3a69127c316e01274550e8a/util/files.go#L100-L109

https://github.com/openpubkey/openpubkey/blob/a11ca00003e5a6cadc8949e72715b85b7f0cfa3a/client/client.go#L61-L65

The private key is generated and stored in `crypto.PrivateKey` which uses `math/big` `big.Int` to store the private key data. Similar to https://github.com/openpubkey/openpubkey/issues/51 the `bit.Int Bytes()` method copies the underlying data to a new byte slice. So there is no way to wipe the data from this object once it is copied in.

**Comment by EthanHeilman** [comment]
@mrjoelkamp Is there any further action to take? Should we close this issue?

**Comment by mrjoelkamp** [comment]
> @mrjoelkamp Is there any further action to take? Should we close this issue?

I am not aware of any practical action to take to remediate this now.  Ok to close.
