### ISSUE TITLE
How do we deal with missing/non-unique `kid` on JWKS endpoint?

### ISSUE THREAD

**Issue by kipz** [openpubkey/openpubkey#61]
In implementing a ledger for OIDC public key, we've found that according to spec, the `kid` is only mandatory if there is more than one key on the JWKS endpoint, and only needs to be unique for each HTTP response on that endpoint. `kid` is obviously super important when trying to lookup the public key given an OPK. I was wondering if adding a hash of the OP public key to the OPK header would solve this? Any other ideas?

**Comment by kipz** [comment]
Relevant thread in slack: https://openssf.slack.com/archives/C060S7FHA3E/p1700039887986919

**Comment by jonnystoten** [comment]
I'm in favor of "Store JKT in unsigned header of the OP". I don't think the cons are very strong for that option.
