### ISSUE TITLE
OIDC ID Token refresh in client

### ISSUE THREAD

**Issue by EthanHeilman** [openpubkey/openpubkey#76]
When available the OpenPubkey client should support the ability to use a refresh token to request an refreshed ID Token. This refreshed ID Token will be stored in an unprotected header of the ID Token.

1. If refresh token returned from OP, client must save this refresh token,
2. If refresh called on client, client must make a refresh call to the OP and save the refreshed ID Token
3. If a refreshed ID Token exists, client must include refreshed ID Token in PK Token as a unprotected header value in the OP signature
4. A PK Token verifier than can be configured require a refreshed ID Token in the PK Token.

This feature does not automatically refreshing an ID Token. It just provides the ability of an implementor to request a refresh.

**Comment by ymarcus93** [comment]
Should this issue also track a 4th step of updating `VerifyPKToken` or associated functions to extract the refreshed ID token from the header and verify it if the initial ID token is expired?

**Comment by EthanHeilman** [comment]
@ymarcus93 Good point. We should have a verifier that can be configured to care or not care about the refreshed ID Token. Added comment above.
